### ISSUE TITLE
use `redis-cli --eval bn.lua` meet some problem

### ISSUE THREAD

**Issue by qyvlik** [user-none/lua-nums#1]
use `redis-cli --eval bn.lua` meet some problem

```
$ redis-cli --eval big-number.lua 0
(error) ERR Error compiling script (new function): user_script:117: unexpected symbol near '<' 
```

The operation `<<` does not seem to support, look https://www.tutorialspoint.com/lua/lua_operators.htm. 
The  bit operation of lua in redis-server side implements by http://bitop.luajit.org/.

How can I run this lua-nums in redis-server ?

**Comment by user-none** [comment]
Lua 5.3 or greater is required because bitwise operations were added to the Lua language in that version. See https://www.lua.org/manual/5.3/manual.html#3.4.2 . redis' implementation is based on Lua 5.1 so you won't be able to use lua-nums until redis updates their support to at least 5.3.
