### ISSUE TITLE
Feature request: ashex() with fixed len

### ISSUE THREAD

**Issue by tst2005** [user-none/lua-nums#10]
Hello,

I probably able to make it mysellf, but you probably be able to write it exactly like you prefer.

My sample of code:
```lua
local u64 = require "nums.uintb".u64
local x = u64("0x6cd2d2bab6fb1b")
local y = x:ashex():lower()
assert(y=="6cd2d2bab6fb1b")
```
I would like to have something like an argument to `ashex(N)` to have a fixed len:
```lua
local u64 = require "nums.uintb".u64
local x = u64("0x6cd2d2bab6fb1b")
local y = x:ashex(16):lower()
assert(y=="006cd2d2bab6fb1b")
```

I think we can add a way to limit the depth of the `reduce()` function to the wanted depth.

What do you think about ?

**Comment by user-none** [comment]
Specifying a width as an argument to `ashex` is already supported. Is it not working for you?

When I run your second code same it works for me. Adding `print(y)` gives me `"006cd2d2bab6fb1b"`.

**Comment by tst2005** [comment]
Oh.... I'm confused.
It run perfectly for my sample.
But I accidentaly read the code of `nums/bn.lua` :
```lua
function M:ashex()
    return tostring_int(self, 16)
end
```
Then the following code will fail :
```lua
local bn = require "nums.bn"
local x = bn("0x6cd2d2bab6fb1b")
local y = x:ashex(16):lower()
assert(y=="006cd2d2bab6fb1b")
```
Is it a missing feature or something else ?

**Comment by user-none** [comment]
Correct `bn` does not have a width for `ashex` but `uint*` does.

**Comment by user-none** [comment]
Added `width` argument for `bn` in f885b27.
