### ISSUE TITLE
possible bug with len_digits()

### ISSUE THREAD

**Issue by tst2005** [user-none/lua-nums#13]
Hello,

`len_digits`: The number of digits in the number in the given base.

Is the "-" is considered as a digit ?

```lua

function M:len_digits(base)
    if not base then
        base = 10
    end
    return #tostring_int(self, base) -- FIXME: possible bug with a negative number ?
end
```

**Comment by user-none** [comment]
> Is the "-" is considered as a digit ?

Currently yes and this is a bug. Fixed in 9a0f7b8 .
