### ISSUE TITLE
failed to clone nums

### ISSUE THREAD

**Issue by hi-flyer** [user-none/lua-nums#19]
trying to install hashings. It says it requires lua-nums.
installed luarocks using apt on ubuntu 20.04
when I try sudo luarocks install lua-nums-scm-1.rockspec 
I get
Cloning into 'lua-nums'...
fatal: unable to connect to github.com:
github.com[0: 140.82.113.4]: errno=Connection timed out

Error: Failed cloning git repository.
I copied the rock
what am I doing wrong.

lua-nums-scm-1.rockspec  is defined as

package = "lua-nums"
version = "scm-1"

source = {
    url = "git://github.com/user-none/lua-nums.git"
}

description = {
    summary    = "Pure Lua number library providing BigNum and fixed width unsigned integer types",
    homepage   = "https://github.com/user-none/lua-nums.git",
    license    = "MIT/X11",
    maintainer = "John Schember <john@nachtimwald.com>"
}

dependencies = {
    "lua >= 5.3"
}

build = {
    type    = "builtin",
    modules = {
        ["nums"]       = "nums/init.lua",
        ["nums.bn"]    = "nums/bn.lua",
        ["nums.uintn"] = "nums/uintn.lua",
        ["nums.uintb"] = "nums/uintb.lua"
    }
}

**Comment by tst2005** [comment]
It is maybe a github issue.

Try with luarocks 3.8.0 that include [a fix](https://github.com/luarocks/luarocks/commit/9ff512e35455939f02eaec2318e3acc77782fdeb) to convert url from "git://" to "git+https://"

or edit the rockspec file
```diff
 source = {
-url = "git://github.com/user-none/lua-nums.git"
+url = "git+https://github.com/user-none/lua-nums.git"
 }
```

**Comment by hi-flyer** [comment]
modified url to the +https and that fixed it.
thanks
